// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EventsEmit2() {
  return window['go']['main']['App']['EventsEmit2']();
}

export function GetBreadList() {
  return window['go']['main']['App']['GetBreadList']();
}

export function GetImageUrlByBreed(arg1) {
  return window['go']['main']['App']['GetImageUrlByBreed'](arg1);
}

export function GetRandomInageUrl() {
  return window['go']['main']['App']['GetRandomInageUrl']();
}

export function WindowFull() {
  return window['go']['main']['App']['WindowFull']();
}
