// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EventsEmit2():Promise<void>;

export function GetBreadList():Promise<Array<string>>;

export function GetImageUrlByBreed(arg1:string):Promise<Array<string>>;

export function GetRandomInageUrl():Promise<string>;

export function WindowFull():Promise<void>;
